# .cnb.yml
dev:
  push:
    # - imports:
    #     - https://cnb.cool/rss1102.cnb/rss1102-secret/-/blob/main/blog.yml
    - services:
        - docker
      stages:
        # 同步代码到 github 仓库
        # - name: sync to github
        #   image: tencentcom/git-sync
        #   settings:
        #     target_url: https://github.com/RSS1102/blog.git
        #     auth_type: https
        #     username: RSS1102
        #     password: ${GITHUB_BLOG_TOKEN}
        #     branch: dev

        # 同名镜像构建&推送
        - name: docker login
          script: docker login docker.cnb.cool -u cnb -p ${BLOG_DOCKER}
        - name: docker build
          script: docker build -t docker.cnb.cool/rss1102/blog:dev .
        - name: docker push
          script: docker push docker.cnb.cool/rss1102/blog:dev